theme: minima
include:
  - robots.txt
  - CKAD-Exam-Tips-general-tips
  - CKAD-Exam-Tips-kubectl-exercises
  - CKAD-Exam-Tips-vim-exercises
  - CKAD-Exam-Tips-bash-exercises
plugins:
  - jekyll-sitemap
baseurl: "/"
google_analytics: G-4N169C6V9C
